stocks:
  outputs:
    dev:
      type: duckdb
      schema: main
      path: 'md:stocks_dev?$MOTHERDUCK_TOKEN'
      threads: 1
      extensions:
        - httpfs

    prod:
      type: duckdb
      schema: main
      path: 'md:stocks'
      threads: 1

    local:
      type: duckdb
      schema: main
      path: 'stocks_local.duckdb'
      threads: 1

  target: dev

