stocks:
  outputs:
    dev:
      type: duckdb
      schema: main
      path: md:stocks_dev
      threads: 1
      extensions:
        - httpfs
    local:
      type: duckdb
      schema: main
      path: stocks_local.db
  target: dev

